### ISSUE TITLE
GCP Workload Identity

### ISSUE THREAD

**Issue by y4h2** [y4h2/personal-notes#17]
Main use case: to access GCP services, avoid exposing service account key.

Bind IAM service account with Kubernetes service account

**Comment by y4h2** [comment]
terraform module
[terraform-google-workload-identity](https://registry.terraform.io/modules/terraform-google-modules/kubernetes-engine/google/latest/submodules/workload-identity) : Bind IAM Service Account with Kubernetes Service Account

**Comment by y4h2** [comment]
# GKE use Workload Identity

- enable workload identity in GKE
- [Create node pool with workload identity config](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#kubectl)
- [Create Pod with tags to use workload identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#verify_the_setup)
```
nodeSelector:
    iam.gke.io/gke-metadata-server-enabled: "true"
```

**Comment by y4h2** [comment]
[To test workload identity in GKE](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#verify_the_setup)

deploy
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: workload-identity-test
  namespace: NAMESPACE
spec:
  containers:
  - image: google/cloud-sdk:slim
    name: workload-identity-test
    command: ["sleep","infinity"]
  serviceAccountName: KSA_NAME
  nodeSelector:
    iam.gke.io/gke-metadata-server-enabled: "true"
```

create pod: `kubectl apply -f wi-test.yaml`

open interactive session
```
kubectl exec -it workload-identity-test \
  --namespace NAMESPACE \
  -- /bin/bash
```

get iam email
```
curl -H "Metadata-Flavor: Google" http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/email
```
