### ISSUE TITLE
GCP managed Promethues

### ISSUE THREAD

**Issue by y4h2** [y4h2/personal-notes#3]
参考： [Measure your golden signals with GKE Managed Prometheus and the nginx-ingress](https://sanderknape.com/2022/05/measure-golden-signals-gke-managed-prometheus-nginx-ingress/)

部署测试组件
```
helm upgrade --install ingress-nginx ingress-nginx \
  --repo https://[kubernetes.github.io/ingress-nginx](http://kubernetes.github.io/ingress-nginx) \
  --namespace ingress-nginx --create-namespace \
  --set controller.metrics.enabled=true
```

部署PodMonitoring
```
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: ingress-nginx-metrics-monitoring
  namespace: ingress-nginx
spec:
  endpoints:
  - interval: 5s
    port: 10254
  selector:
    matchLabels:
      app.kubernetes.io/name): ingress-nginx
```

然后在GCP monitoring page上能看到对应的metrics
![image](https://user-images.githubusercontent.com/5662692/193935319-c2812485-386b-4a57-bd61-bf60383832fa.png)

**Comment by y4h2** [comment]
用GCP官方example测试
- create a normal namespace test with default values.
- kubectl apply GCP's example application in the namespace test. (https://raw.githubusercontent.com/GoogleCloudPlatform/prometheus-engine/v0.4.3-gke.0/examples/example-app.yaml)
- apply GCP PodMonitoring within the namespace test
```yaml
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: prom-example
spec:
  selector:
    matchLabels:
      app: prom-example
  endpoints:
  - port: metrics
    interval: 30s
```
- then I am able to see the metrics in GCP Monitoring's metrics explorer.
