### ISSUE TITLE
GCP IAM role map to Kubernetes RBAC

### ISSUE THREAD

**Issue by y4h2** [y4h2/personal-notes#5]
[Authorize actions in clusters using role-based access control](https://cloud.google.com/kubernetes-engine/docs/how-to/role-based-access-control)
Kubernetes的Role支持四种binding (https://cloud.google.com/kubernetes-engine/docs/how-to/role-based-access-control#rolebinding)
- GCP User email address
- Kubernetes ServiceAccount
- IAM service account
- Google Group address

最小的权限是`container.clusters.get`
>In almost all cases, Kubernetes RBAC can be used instead of IAM. GKE users require at minimum, the container.clusters.get IAM permission in the project that contains the cluster. This permission is included in the container.clusterViewer role, and in other more highly privileged roles. The container.clusters.get permission is required for users to authenticate to the clusters in the project, but does not authorize them to perform any actions inside those clusters. Authorization may then be provided by either IAM or Kubernetes RBAC.

例子：
```yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader-binding
  namespace: accounting
subjects:
# Google Cloud user account
- kind: User
  name: janedoe@example.com
# Kubernetes service account
- kind: ServiceAccount
  name: johndoe
# IAM service account
- kind: User
  name: test-account@test-project.iam.gserviceaccount.com
# Google Group
- kind: Group
  name: accounting-group@example.com
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
```

现在的主要问题是怎么让Role能binding到IAM的role group中
