### ISSUE TITLE
Kubernetes Ingress

### ISSUE THREAD

**Issue by y4h2** [y4h2/personal-notes#50]
![image](https://user-images.githubusercontent.com/5662692/199367070-28dba981-4504-4eab-a0a4-d82582838294.png)

ingress expose service to external
- acts as an entry point
- define routing rules

example
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /foo
        pathType: Prefix
        backend:
          service:
            name: foo-service
            port:
              number: 3000
      - path: /bar
        pathType: Prefix
        backend:
          service:
            name: bar-service
            port:
              number: 6000
  - host: foo.example.com
    http:
      paths:
      - pathType: Prefix
        path: "/foo"
        backend:
          service:
            name: foo-service-2
            port:
              number: 80
  - host: "*.foo.example.com"
    http:
      paths:
      - pathType: Prefix
        path: "/foo"
        backend:
          service:
            name: foo-service-3
            port:
              number: 8080
```
